dist: bionic
language: cpp
compiler:
  - clang
  - gcc
    
addons:
  apt:
    packages:
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libxi-dev
      - mesa-common-dev
      - libgl1-mesa-dev

before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
script:
  - make

