#ifndef FORMA_VERSION_HPP_
#define FORMA_VERSION_HPP_

#define FORMA_VERSION_MAJOR 0
#define FORMA_VERSION_MINOR 1
#define FORMA_VERSION_PATCH 6
#define FORMA_VERSION_TWEAK 
#define FORMA_VERSION "0.1.6"

#endif // FORMA_VERSION_HPP_
